version: '3'
services:
  apache1:
    image: httpd
    volumes:
      - ./web/login.html:/usr/local/apache2/htdocs/index.html
    ports:
      - "8081:80"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8050:80"

  mysql:
    image: mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: tiempoEuskadi
      MYSQL_USER: joseAdmin
      MYSQL_PASSWORD: joseluis
      MYSQL_ROOT_PASSWORD: root
    volumes:
        - './BBDD/:/var/lib/mysql'
    ports:
      - "3306:3306"
 
  laravelpassport:
    image: markosmartinez/laravelpassport-php8.2
    container_name: LaravelPassport
    volumes:
      - ./tiempoEuskadi-app/:/var/www/html/
      # Por defecto el puerto utilizado en laravel es el 8000
    ports:
      - "8080:8000"

  