version: '3.9'
services:
  apache1:
    image: httpd:latest
    volumes:
      - ./web:/usr/local/apache2/htdocs/
    ports:
      - "8081:80"

  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  mysql:
    image: mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: tiempoeuskadiApp
      MYSQL_USER: jose
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
        - ./BBDD/:/var/lib/mysql
    ports:
      - "3306:3306"
 
  laravelpassport:
    image: markosmartinez/laravelpassport-php8.2
    container_name: LaravelPassport
    volumes:
      - ./tiempoEuskadi-app/:/var/www/html/
      # Por defecto el puerto utilizado en laravel es el 8000
    ports:
      - "8082:8000"
    depends_on:
      - mysql

  laravelApi:
    image: bitnami/laravel
    container_name: LaravelApi
    volumes:
      - ./LaravelApi/:/var/www/html/
    ports:
      - "8083:8000"
    depends_on:
      - mysql

  