version: '3'
services:
  apache1:
    image: httpd
    volumes:
      - ./index1.html:/usr/local/apache2/htdocs/index.html
    ports:
      - "8081:80"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AppWebJose
      MYSQL_USER: joseRoot
      MYSQL_PASSWORD: jooseRoot
    ports:
      - "3306:3306"